# Generated by Django 5.0.1 on 2024-01-12 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    
    ]
    operations = [
        migrations.CreateModel(
            name='CoreModule',
            fields=[
                ('hardware_id', models.CharField(max_length=24, primary_key=True, serialize=False, verbose_name='Unique hardware ID')),
                ('firmware', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Firmware Version')),
                ('bootloader', models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='Bootloader Version')),
                ('v0Conv', models.FloatField(default=108, help_text='Voltage 0 conversion', verbose_name='v0Conv')),
                ('v1Conv', models.FloatField(default=35.5, help_text='Voltage 1 conversion', verbose_name='v1Conv')),
                ('v2Conv', models.FloatField(default=71, help_text='Voltage 2 conversion', verbose_name='v2Conv')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pi/Core Module',
                'db_table': 'tk_core_module',
            },
        ),
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tk_bike_id', models.IntegerField(db_index=True, help_text='TrueKinetix bike id', unique=True, verbose_name='Bike ID')),
                ('device_type', models.SmallIntegerField(choices=[(0, 'Unknown device'), (1, 'TrueBike'), (2, 'Trainer')], default=0, help_text='Device type is set from License Capability', verbose_name='Device Type')),
                ('sensorData', models.TextField(blank=True, help_text='TB Sensor data', null=True, verbose_name='TbSensor')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('core_module', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swaper.coremodule')),
            ],
            options={
                'verbose_name': 'Bike',
                'db_table': 'tk_bike',
            },
        ),
    ]
